create schema library;
create table library.person
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  varchar(100) NOT NULL UNIQUE,
    birth_year int          NOT NULL
);
create table library.book
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(100) NOT NULL,
    author      varchar(100) NOT NULL,
    year        int          NOT NULL,
    reader_name varchar      REFERENCES library.person (full_name) ON DELETE SET NULL
);